[package]
name = "rust_tk_macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.18", features = ["full", "extra-traits"] }
quote = "1.0.28"